CLI_CONFIG = {
    'ans_hosts_path': '/etc/pcli/ansible/hosts',
    'ans_playbooks_path': '/etc/pcli/ansible/playbooks/',
    'ans_root': '/etc/pcli/ansible/',
    'iam_cred_path': '/home/ec2-user/.iam_credentials',
    'inst_config_path': '/etc/pcli/terraform/inst_config.json',
    'inst_cred_path': '/etc/pnode/data/.node-cred',
    'inst_user': 'ec2-user',
    'inst_state_path': '/etc/pcli/.pcli/inst-state.pickle',
    'pcli_config_path': '/etc/pcli/.pcli/',
    'pcli_log_path': '/var/log/pcli/pcli.log',
    'pcli_ssh_key_path': '~/.ssh/pcli/',
    'pnetwork_gpg_key': 'https://release-server.nsw.p.network/gpg/pnetwork.asc',
    'pnetwork_pcli_url': 'https://release-server.nsw.p.network/pcli/',
    'pnetwork_pnode_url': 'https://release-server.nsw.p.network/pnode/rpm/',
    'pnetwork_pnode_url_dev': 'https://release-server.nsw.p.network/dev/pnode/rpm',
    'tf_config_dir': '/etc/pcli/terraform/',
    'tf_main_orig_path': '/etc/pcli/terraform/main.tf.orig',
    'tf_output_orig_path': '/etc/pcli/terraform/output.tf.orig',
    'tf_state_path': '/etc/pcli/terraform/',
    'tf_variables_orig_path': '/etc/pcli/terraform/variables.tf.json.orig'
}
